### ISSUE TITLE
Building the container behind a proxy

### ISSUE THREAD

**Issue by javixeneize** [jfloff/alpine-python#10]
Hi

One interesting question... How to build a container behind a proxy?

When running pip to install the dependencies, it cant resolve the host, so you need to add a proxy in the docker file

While using a ubuntu image, exporting the proxy is easy (ENV http_proxy .....), using alpine or python templates doesnt work

Any idea on how to solve this problem?

**Comment by jfloff** [comment]
Nice question. A quick google search gave me this discussion at the official Alpine docker image: https://github.com/gliderlabs/docker-alpine/issues/191#issuecomment-246944011

Do you think you could test this approach with a custom Dockerfile and provide feedback?

**Comment by jfloff** [comment]
Were you able to reach a solution @javixeneize ?

**Comment by javixeneize** [comment]
Hi. Sorry, yes, it works fine configuring the proxy inside

Thanks

**Comment by jfloff** [comment]
Could you give some details on how you made it? Maybe write those instructions in the README and PR?

**Comment by javixeneize** [comment]
Hi

It was really straightforward. Just add a line to the docker file to
configure the proxy :)

FROM alpine:3.3
ENV http_proxy http://proxy.com
ENV https_proxy http://proxy.com
......

Thanks

**Comment by gbarco** [comment]
I would like to reopen threads like this one but requiring an answer that allows another person to run the same image without modifying and rebuilding from Dockerfile.

ENV in Dockerfile is so local, hacky and non portable it cripples Docker to uselessness in corporations.
Also incomplete since I assume you also will need a proxy to get your base image.

I expect proxy on host talks or something level of conversation to reach a solution.

**Comment by jfloff** [comment]
I actually stumped on this the other day: use `ARG` during the build. More details here: https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables-build-arg

Taken from the link above: `$ docker build --build-arg HTTP_PROXY=http://10.20.30.2:1234 .`

I think this fits your scenario.

**Comment by Multihuntr** [comment]
I would like to second using the `--build-arg` flag instead of ENV in the Dockerfile. By setting the `--build-arg` correctly, you set the environment variable only for build time. 
By setting the environment variables to those within the Dockerfile, you are saying that it will always have to use those proxy settings (it's not so easy to unset an environment variable in docker), even in a running container, or any derivative images.
I got caught by this one yesterday.
