### ISSUE TITLE
Can't install openblas because hacky repository replacement

### ISSUE THREAD

**Issue by paulochf** [jfloff/alpine-python#24]
I was trying to use this to create an image for a Python-sci container using slim's command line as follows:

```
docker run --rm -ti jfloff/alpine-python:recent-slim \
-a libstdc++ \
-a g++ \
-a gfortran \
-a openblas-dev \
-a openblas \
-p Flask==0.12.2 \
-p gevent==1.2.2 \
-p gunicorn==19.7.1 \
-p pandas==0.22.0 \
-p scikit-learn==0.19.1
```

but it didn't take too long to get an error.

```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  openblas (missing):
    required by: world[openblas]
  openblas-dev (missing):
    required by: world[openblas-dev]
```

After forking and tweaking a little, I realized that the following part was the problem:

```
  && echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" > /etc/apk/repositories \
  && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  && echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \

  # Add the packages, with a CDN-breakage fallback if needed
  && apk add --no-cache $PACKAGES || \
    (sed -i -e 's/dl-cdn/dl-4/g' /etc/apk/repositories && apk add --no-cache $PACKAGES) \

  # turn back the clock -- so hacky!
  && echo "http://dl-cdn.alpinelinux.org/alpine/v$ALPINE_VERSION/main/" > /etc/apk/repositories \
  # && echo "@edge-testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
  # && echo "@edge-community http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  # && echo "@edge-main http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
```

My solution was to turn off the "turn back the clock" entirely.

As I don't know too much about docker, I can't give any improvement suggestions right now. I just wanted to point the problem here to let people (and you) about it.

Thanks!

**Comment by jfloff** [comment]
Hello,

First of all, thank you for the input. So let's me explain the hacky procedure. 

Alpine has multiple package repositories. Sometimes we have to add some of these extra package repositories to add some of the packages we want to have. The thing is, there are multiple problems that I have personally faced with this, here are some:
- Different versions on different package repositories cause conflicts when we have both the repositories enabled. 
- Packages dependencies that only exist on some other package repository -- this is what you've experienced

Due to these issues, I've left the choice to enable these extra package repositories to each user, and let users deal with these problems themselves. The only package repostirory that I enable is the default one: `http://dl-cdn.alpinelinux.org/alpine/v$ALPINE_VERSION/main/`

Said that, I took the time to debug your scenario, which is illustrative of some of the problems that Alpine package repositories face: [`openblas` is only available on `community` repository](https://pkgs.alpinelinux.org/packages?name=*openblas*&branch=v3.7&repo=community)

I've built a small Dockerfile for the set of packages that you've wrote on your message:
```
FROM jfloff/alpine-python:recent

# install needed packages
RUN set -ex ;\
    echo "@community http://dl-cdn.alpinelinux.org/alpine/v$ALPINE_VERSION/community" >> /etc/apk/repositories ;\
    apk add --no-cache --update libstdc++ \
                                g++ \
                                gfortran \
                                openblas-dev@community \
                                openblas@community \
                                ;\
    rm /var/cache/apk/*

RUN pip install --no-cache Flask==0.12.2 \
                           gevent==1.2.2 \
                           gunicorn==19.7.1 \
                           pandas==0.22.0 \
                           scikit-learn==0.19.1 \
                           ;\
```

Last note, I really don't recommend the `slim` tag for the novice docker user. Get the habit of building your own Dockerfiles. The `slim` tag has its use, but it more for the advanced user IMHO.


PS: In fact I'm using the `edge` repository on the image but should be using the `3.7`. I will change that and I will also try adding the `3.7` community by default, for python is almost always needed. Let's just hope we don't get into version conflict issues :/

**Comment by paulochf** [comment]
> PS: In fact I'm using the edge repository on the image but should be using the 3.7.

Yeah, that was my point! But I agree with you, and I thank you for the explanation.
