### ISSUE TITLE
alpine-python:3.4 images currently contain 3.5

### ISSUE THREAD

**Issue by zackelan** [jfloff/alpine-python#3]
Repro:
$ docker rmi jfloff/alpine-python:3.4; docker pull jfloff/alpine-python:3.4 (force re-download the newest image if it's already cached)
$ docker run --rm jfloff/alpine-python:3.4 python --version

Expected:
Python 3.4.x

Actual:
"Python 3.5.2"

The issue seems to be that the Dockerfile just runs "apk add python3", and Alpine 3.4 is currently shlpping 3.5.2. I can confirm this with "docker run --rm -it alpine:3.4 sh" then "apk add --no-cache python3" which installs 3.5.2-r0.

**Comment by jfloff** [comment]
Great catch. This is kind-of a known issue since in Alpine APK you are not able to install a specific (older) version of a package (for more info, see the [new section in README](https://github.com/jfloff/alpine-python#todo)), hence we are always forced to install the version that apk provides us. 

I've managed to correct this for Python 3.4 since there are packages specific for 3.4 version. Here is a rundown of changes:
- Fixed python 3.4 tag
- A new tag for the `latest` Alpine APK python version (3.5 atm)

I'm also pinging @tprobinson to do a quick review of this changes. I had to remove the PYTHON_MAJOR_VERSION since I wasn't able to really abstract the version, if you could dwell a bit on how to provide multiple python versions (see [README]((https://github.com/jfloff/alpine-python#todo) for more info) would be awesome. I also had a spike in the size of the new `3.4-slim` image. If you could take a look at both these problems would be amazing! Thanks in advance! 👍

**Comment by tprobinson** [comment]
With the release of Alpine 3.4.4, Python 3.4 was replaced with Python 3.5 in the package repositories, under the same name of `python3`. For some reason they also replaced it in the 3.3 release branch, and there's no way to access the older package. The new `python3.4` package in the testing branch is unfortunately just larger, installing at 92.96MB, meaning this size spike is unavoidable for 3.4. I don't see any breaking changes noted in the 3.4 -> 3.5 changelog for Python, so anything that worked on 3.4 should work on 3.5 at least.

I'm doing some more in-depth investigation into how the official images do it, so we'll see if we can get a more robust build process out of what I learn there. I'll submit a pull when that's done.

**Comment by jfloff** [comment]
Thank you so much for looking into it! The alternative instead of relying on the Alpine APK, is to compile from source, just like python does in its [official images](https://github.com/docker-library/python/blob/master/3.4/alpine/Dockerfile). But I'm afraid that way we will end up having no benefit (size wise) over the official images. An option would be to streamline the same process the official images do, but trying to achieve lower image size.
